[package]
name = "fixedstr"
version = "0.4.1"
authors = ["Chuck Liang"]
edition = "2021"
license = "MIT"
description = "strings of constant maximum size that can be copied and stack allocated using const generics"
repository = "https://github.com/chuckcscccl/fixedstr/"
keywords = ["string","no-std"]


[features]
default = ["std"]
serde=["dep:serde"]
std=[]
pub_tstr=[]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde={version="1", optional=true, default-features=false}
