[package]
name = "fixedstr"
version = "0.2.6"
edition = "2018"
license = "MIT"
description = "strings of constant maximum size that can be copied and stack allocated, using Rust's new const generics"
repository = "https://github.com/chuckcscccl/fixedstr/"
keywords = ["string"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
